#!/bin/sh

### This script will create a new DMG file for distribution

if [ ! -d "build" ]; then
  mkdir build
fi

if [ -e "build/FCPXHacks.dmg" ]; then
	rm "build/FCPXHacks.dmg"
fi

LINK="false"
# Check if we are in 'link' mode currently
if [ -L "$HOME/.hammerspoon" ]; then
	LINK="true"
fi

# Install the latest version
./install-hs

dmgcanvas dmg/dmg_template.dmgCanvas "build/FCPX Hacks.dmg" \
	-setFilePath init.lua src/init.lua \
	-setFilePath hs src/hs \

if [ "$LINK" == "true" ]; then
	./link-hs
fi
